name: 'Install Node.js'
description: 'Install Node.js with specified version'

inputs:
  node-version:
    description: 'Node.js version to install'
    required: false
    default: '18'

runs:
  using: 'composite'
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ inputs.node-version }}
    
    - name: Verify installation
      shell: bash
      run: |
        node --version
        npm --version