{{- $annotaions := .Values.annotaions -}}
{{- $labels := .Values.labels -}}
{{- $helmResourcePolicy := .Values.helmResourcePolicy -}}
{{- range $key := .Values.namespaces }}
{{- range $env := .Values.env}}
---
apiVersion: v1
kind: Namespace
metadata:
  name: "{{ $key }}-{{ $env }}"
  labels:
    router: "{{ $env }}"
{{- with $labels }}
    {{ toYaml . | nindent 4 }}
{{- end }}
{{- with $annotaions }}
  annotaions:
    kubernetes.io/description: "{{ $key }}-{{ $env }}"
{{ toYaml . | indent 4 }}
{{- end }}
{{- end }}
{{- end -}}

