name: Create Repository
description: 'Reusable workflow to create a GitHub repository'

inputs:
  repo_name:
    description: 'Name of the repository to create'
    required: true
  repo_description:
    description: 'Description of the repository'
    required: false
  is_private:
    description: 'Whether the repository should be private'
    required: false
  github_token:
    description: 'GitHub token for authentication'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Create Repository
      env:
        GH_TOKEN: ${{ inputs.github_token }}
      shell: bash
      run: |
        // use github api to create repo
        curl -H "Authorization: token $GH_TOKEN" \
             -d "{\"name\":\"${{ inputs.repo_name }}\", \"description\":\"${{ inputs.repo_description }}\", \"private\":${{ inputs.is_private }}}" \
             https://api.github.com/orgs/rahulraj2/repos