name: Create Repository
description: 'Reusable workflow to create a GitHub repository'

inputs:
  repo_name:
    description: 'Name of the repository to create'
    required: true
  repo_description:
    description: 'Description of the repository'
    required: false
  is_private:
    description: 'Whether the repository should be private'
    required: false
  github_token:
    description: 'GitHub token for authentication'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Create Repository
      env:
        GH_TOKEN: ${{ inputs.github_token }}
      shell: bash
      # Using GitHub API to create a repository
      run: |
        # Using GitHub API to create a repository
        response=$(curl -s -w "\n%{http_code}" -H "Authorization: token $GH_TOKEN" \
             -d "{\"name\":\"${{ inputs.repo_name }}\", \"description\":\"${{ inputs.repo_description }}\", \"private\":${{ inputs.is_private }}}" \
             https://api.github.com/user/repos)
        
        # Extract HTTP status code and response body
        http_code=$(echo "$response" | tail -n1)
        body=$(echo "$response" | head -n-1)
        
        echo "HTTP Status Code: $http_code"
        echo "Repository creation response:"
        echo "$body"
        
        # Check if status code is not 201 (Created)
        if [ "$http_code" != "201" ]; then
          echo "Error: Failed to create repository. HTTP Status: $http_code"
          echo "Response: $body"
          exit 1
        fi
        
        # Parse and extract key information from JSON response
        repo_url=$(echo "$body" | grep -o '"html_url":"[^"]*' | cut -d'"' -f4)
        repo_id=$(echo "$body" | grep -o '"id":[0-9]*' | head -1 | cut -d':' -f2)
        
        echo "Repository URL: $repo_url"
        echo "Repository ID: $repo_id"